#!/bin/bash

set -ex

if (( "${#DOTFILES_FETCH[*]}" < 1 ))
then
    DOTFILES_FETCH=(cat)
fi

if (( "${#DOTFILES_LOCATION[*]}" < 1 ))
then
    DOTFILES_LOCATION=`dirname "${BASH_SOURCE[0]}"`
fi

if [[ ! -z "${DOTFILES_REMOTE}" ]]
then
    DOTFILES_FETCH=(curl -sL)
    DOTFILES_LOCATION="https://raw.githubusercontent.com/burgerdev/dotfiles/master"
fi


function install {
    "${DOTFILES_FETCH[@]}" "${DOTFILES_LOCATION}/$1" > "$2"
}


# top-level rc files

for rc in `"${DOTFILES_FETCH[@]}" "${DOTFILES_LOCATION}/.autogenerated/toplevelrcfiles"`
do
    install "${rc}" "${HOME}/.${rc}"
done

# config

configdir="config" 

## fish dir

fishdir="${configdir}/fish"
fishtargetdir="${HOME}/.${fishdir}"

mkdir -p "${fishtargetdir}/functions"

for f in `"${DOTFILES_FETCH[@]}" "${DOTFILES_LOCATION}/.autogenerated/fish.functions"`
do
   install "$f" "${HOME}/.$f" 
done
